### ISSUE TITLE
Issue with a wrong SQL syntax 

### ISSUE THREAD

**Issue by KevinSkull** [KevinSkull/HydraFoods#13]
the SQL syntax code seems to right, no reason for it to show that.

**Comment by SharonGreally** [comment]
Kevin, regarding the issue you raised above, can you clarify what you mean when you say "no reason for it to show that".   If the code is generating an error, can you confirm what the error is?

**Comment by KevinSkull** [comment]
Issue has been fixed due to code overhaul.
